import { StyleSheet } from 'react-native';

export const cakesStyles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 16,
        backgroundColor: '#faf5ff',
    },
    scrollContent: {
        paddingBottom: 24,
    },
    title: {
        fontSize: 26,
        fontWeight: '800',
        marginBottom: 12,
        color: '#1a1a1a',
    },
    viewModeRow: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 10,
    },
    viewModeButton: {
        flex: 1,
        paddingVertical: 6,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#ccc',
        alignItems: 'center',
        backgroundColor: '#fff',
    },
    viewModeButtonActive: {
        backgroundColor: '#e91e63',
        borderColor: '#e91e63',
    },
    viewModeButtonText: {
        color: '#333',
        fontWeight: '500',
    },
    viewModeButtonTextActive: {
        color: '#fff',
        fontWeight: '600',
    },
    formSection: {
        marginBottom: 16,
        gap: 10,
        backgroundColor: '#fff',
        borderRadius: 12,
        padding: 12,
        borderWidth: 1,
        borderColor: '#f0d7eb',
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 6,
        elevation: 2,
    },
    input: {
        borderWidth: 1,
        borderColor: '#e0c4d9',
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 10,
        backgroundColor: '#fff',
        fontSize: 14,
    },
    label: {
        fontWeight: '600',
        marginTop: 4,
    },
    shapeRow: {
        flexDirection: 'row',
        gap: 8,
        marginBottom: 4,
    },
    shapeButton: {
        flex: 1,
        paddingVertical: 6,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: '#ccc',
        alignItems: 'center',
    },
    shapeButtonActive: {
        backgroundColor: '#e91e63',
        borderColor: '#e91e63',
    },
    shapeButtonText: {
        color: '#333',
    },
    shapeButtonTextActive: {
        color: '#fff',
        fontWeight: '600',
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        marginVertical: 10,
        color: '#333',
    },
    sectionTitleCompact: {
        fontSize: 18,
        fontWeight: '700',
        marginTop: 0,
        marginBottom: 2,
        color: '#333',
    },
    ingRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 6,
        paddingVertical: 4,
    },
    ingName: {
        flex: 1,
    },
    ingInput: {
        width: 80,
        borderWidth: 1,
        borderColor: '#e0c4d9',
        borderRadius: 8,
        paddingHorizontal: 8,
        paddingVertical: 6,
        marginLeft: 8,
        textAlign: 'right',
        backgroundColor: '#fff',
    },
    costLabel: {
        fontSize: 16,
        fontWeight: '600',
        marginBottom: 8,
    },
    gainLabel: {
        fontSize: 15,
        fontWeight: '700',
        color: '#2b8a5b',
        marginBottom: 10,
    },
    gainLabelNegative: {
        color: '#c0392b',
    },
    emptyText: {
        color: '#777',
        marginBottom: 4,
    },
    cakeRow: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#eee',
    },
    clientDot: {
        width: 6,
        height: 32,
        borderRadius: 3,
        marginRight: 8,
        backgroundColor: '#ccc',
    },
    cakeName: {
        fontSize: 14,
        fontWeight: '500',
    },
    cakeSubtitle: {
        color: '#555',
        fontSize: 11,
    },
    cakeStatusBadgeRow: {
        flexDirection: 'row',
        gap: 6,
        marginTop: 1,
        flexWrap: 'wrap',
    },
    cakeStatusBadge: {
        paddingHorizontal: 8,
        paddingVertical: 3,
        borderRadius: 999,
    },
    cakeStatusBadgePaid: {
        backgroundColor: '#ffe0ef',
    },
    cakeStatusBadgeDelivered: {
        backgroundColor: '#ddf5e8',
    },
    cakeStatusBadgeText: {
        fontSize: 10,
        fontWeight: '700',
        color: '#444',
    },
    cakeCost: {
        fontSize: 15,
        fontWeight: '700',
    },
    cakeCostPaid: {
        color: '#e91e63',
    },
    cakeCostDelivered: {
        color: '#1d8f6a',
    },
    cakeProfitText: {
        marginTop: 1,
        fontSize: 11,
        fontWeight: '700',
        color: '#2b8a5b',
    },
    calendarHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: 4,
        marginTop: 4,
    },
    calendarMonth: {
        fontSize: 16,
        fontWeight: '600',
        color: '#333',
    },
    calendarNavButton: {
        minWidth: 32,
        minHeight: 28,
        paddingHorizontal: 6,
        paddingVertical: 3,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#ccc',
        alignItems: 'center',
        justifyContent: 'center',
    },
    calendarNavText: {
        fontSize: 14,
    },
    calendarDaysRow: {
        marginBottom: 0,
    },
    calendarDaysContent: {
        alignItems: 'center',
        paddingBottom: 0,
    },
    dayChip: {
        alignItems: 'center',
        justifyContent: 'center',
        paddingHorizontal: 7,
        paddingVertical: 3,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#ccc',
        marginRight: 5,
        backgroundColor: '#fff',
        minWidth: 36,
        height: 44,
    },
    dayChipSelected: {
        backgroundColor: '#e91e63',
        borderColor: '#e91e63',
    },
    dayChipWeek: {
        fontSize: 9,
        color: '#555',
    },
    dayChipLabel: {
        fontSize: 12,
        fontWeight: '600',
        color: '#333',
    },
    filtersContainer: {
        marginTop: 0,
        marginBottom: 10,
        gap: 8,
    },
    statusFilterRow: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        gap: 3,
    },
    statusFilterButton: {
        paddingHorizontal: 9.1,
        paddingVertical: 5,
        borderRadius: 999,
        borderWidth: 1,
        borderColor: '#f0c9dc',
        backgroundColor: '#fff',
    },
    statusFilterButtonActive: {
        backgroundColor: '#e91e63',
        borderColor: '#e91e63',
    },
    statusFilterButtonText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#9a456a',
    },
    statusFilterButtonTextActive: {
        color: '#fff',
    },
    searchBox: {
        flexDirection: 'row',
        alignItems: 'center',
        minHeight: 48,
        borderWidth: 1,
        borderColor: '#e0c4d9',
        borderRadius: 12,
        backgroundColor: '#fff',
        paddingHorizontal: 12,
    },
    searchIcon: {
        marginRight: 8,
    },
    filterRow: {
        flexDirection: 'row',
        gap: 8,
    },
    filterInput: {
        flex: 1,
        paddingHorizontal: 0,
        paddingVertical: 0,
        minHeight: 44,
        backgroundColor: 'transparent',
        fontSize: 16,
        color: '#111',
    },
    monthScroll: {
        flex: 1,
    },
    summaryCard: {
        marginBottom: 5,
        padding: 10,
        borderRadius: 18,
        backgroundColor: '#fff',
        borderWidth: 1,
        borderColor: '#f0d7eb',
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 8,
        elevation: 2,
    },
    summaryHeaderRow: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        gap: 12,
        marginBottom: 12,
    },
    summaryTitle: {
        fontSize: 13,
        fontWeight: '800',
        color: '#3b2330',
    },
    summarySubtitle: {
        marginTop: 2,
        fontSize: 11,
        color: '#8a6a7c',
    },
    summaryToggleRow: {
        flexDirection: 'row',
        gap: 6,
    },
    summaryToggleButton: {
        paddingHorizontal: 10,
        paddingVertical: 6,
        borderRadius: 999,
        backgroundColor: '#fff3f8',
    },
    summaryToggleButtonActive: {
        backgroundColor: '#e91e63',
    },
    summaryToggleButtonText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#a54d75',
    },
    summaryToggleButtonTextActive: {
        color: '#fff',
    },
    summaryAmount: {
        fontSize: 20,
        fontWeight: '800',
        color: '#1f1f1f',
    },
    summaryMeta: {
        marginTop: 4,
        fontSize: 11,
        color: '#78606f',
    },
    monthContent: {
        paddingBottom: 24,
    },
    monthViewContainer: {
        flex: 1,
    },
    calendarBlock: {
        marginBottom: 6,
    },
    daySection: {
        flex: 1,
        marginTop: 0,
    },
    daySectionDate: {
        marginBottom: 6,
        fontSize: 12,
        fontWeight: '700',
        color: '#7a5e6e',
    },
    monthListScroll: {
        flex: 1,
    },
    monthListContent: {
        paddingBottom: 20,
    },
    photoPreview: {
        width: 88,
        height: 88,
        borderRadius: 12,
    },
    photoActionRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 12,
        marginTop: 8,
        marginBottom: 14,
    },
    photoPickerButton: {
        width: 72,
        height: 72,
        borderRadius: 16,
        borderWidth: 1,
        borderColor: '#f2bdd5',
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 6,
        elevation: 2,
    },
    photoPickerButtonText: {
        fontSize: 12,
        fontWeight: '700',
        color: '#e91e63',
    },
    photoPreviewCard: {
        position: 'relative',
        borderRadius: 14,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#f2bdd5',
        backgroundColor: '#fff',
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 6,
        elevation: 2,
    },
    photoPreviewBadge: {
        position: 'absolute',
        right: 6,
        bottom: 6,
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: 'rgba(0,0,0,0.55)',
        alignItems: 'center',
        justifyContent: 'center',
    },
    photoPlaceholderCard: {
        width: 88,
        height: 88,
        borderRadius: 14,
        borderWidth: 1,
        borderColor: '#ead4e0',
        borderStyle: 'dashed',
        backgroundColor: '#fff',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
    },
    photoPlaceholderText: {
        fontSize: 12,
        color: '#a1768d',
        fontWeight: '600',
    },
    expandedPhotoPreview: {
        width: '90%',
        height: '72%',
        borderRadius: 12,
    },
    saveCakeButton: {
        minHeight: 52,
        borderRadius: 14,
        backgroundColor: '#e91e63',
        alignItems: 'center',
        justifyContent: 'center',
        flexDirection: 'row',
        gap: 8,
        shadowColor: '#e91e63',
        shadowOpacity: 0.22,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 12,
        elevation: 4,
    },
    saveCakeButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: '700',
    },
    headerActionsRow: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    headerIconButton: {
        marginRight: 12,
    },
    detailOverlay: {
        position: 'absolute',
        top: 0,
        left: 0,
        right: 0,
        bottom: 0,
        backgroundColor: 'rgba(0,0,0,0.2)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 16,
    },
    detailCard: {
        width: '100%',
        maxHeight: '88%',
        backgroundColor: '#fff',
        borderRadius: 20,
        paddingHorizontal: 12,
        paddingTop: 10,
        paddingBottom: 10,
        borderWidth: 1,
        borderColor: '#f0d7eb',
        shadowColor: '#000',
        shadowOpacity: 0.08,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 14,
        elevation: 4,
    },
    detailCardContent: {
        paddingBottom: 16,
    },
    detailHeaderRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 6,
    },
    detailDate: {
        fontSize: 13,
        fontWeight: '600',
    },
    detailClient: {
        fontSize: 13,
    },
    detailTitle: {
        fontSize: 16,
        fontWeight: '700',
        marginTop: 0,
        marginBottom: 3,
    },
    detailTopSection: {
        flexDirection: 'row',
        alignItems: 'flex-start',
        justifyContent: 'space-between',
        gap: 10,
        marginBottom: 5,
    },
    detailTitleBlock: {
        flex: 1,
    },
    detailTopMeta: {
        fontSize: 12,
        fontWeight: '600',
        color: '#8a6a7c',
    },
    detailPhotoCompactWrapper: {
        width: 72,
        height: 72,
        borderRadius: 14,
        overflow: 'hidden',
        borderWidth: 1,
        borderColor: '#f2bdd5',
        backgroundColor: '#fff',
    },
    detailPhotoCompact: {
        width: '100%',
        height: '100%',
    },
    cakeStatusRow: {
        flexDirection: 'row',
        gap: 6,
        marginBottom: 5,
    },
    cakeStatusButton: {
        flex: 1,
        minHeight: 34,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#f2bdd5',
        backgroundColor: '#fff7fb',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 4,
        paddingHorizontal: 8,
    },
    cakeStatusButtonPaid: {
        backgroundColor: '#e91e63',
        borderColor: '#e91e63',
    },
    cakeStatusButtonDelivered: {
        backgroundColor: '#2b8a5b',
        borderColor: '#2b8a5b',
    },
    cakeStatusButtonText: {
        fontSize: 11,
        fontWeight: '700',
        color: '#444',
    },
    cakeStatusButtonTextActive: {
        color: '#fff',
    },
    duplicateCakeButton: {
        minHeight: 36,
        borderRadius: 10,
        borderWidth: 1,
        borderColor: '#f2bdd5',
        backgroundColor: '#fff',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 6,
        marginBottom: 5,
    },
    duplicateCakeButtonText: {
        color: '#e91e63',
        fontSize: 13,
        fontWeight: '700',
    },
    detailCloseText: {
        color: '#e91e63',
        fontWeight: '600',
        fontSize: 13,
    },
    detailLinesContainer: {
        marginTop: 0,
        marginBottom: 0,
        gap: 0,
    },
    detailSectionLabel: {
        fontSize: 12,
        fontWeight: '800',
        color: '#7a5e6e',
        marginBottom: 3,
        letterSpacing: 0.4,
    },
    detailIngredientsScroll: {
        minHeight: 140,
        maxHeight: 300,
        borderWidth: 1,
        borderColor: '#f3dbe7',
        borderRadius: 14,
        backgroundColor: '#fff9fc',
        marginBottom: 1,
    },
    detailIngredientsContent: {
        paddingHorizontal: 10,
        paddingVertical: 0,
    },
    detailPhotoWrapper: {
        alignItems: 'center',
        marginBottom: 8,
    },
    detailPhoto: {
        width: 128,
        height: 128,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#ccc',
    },
    detailLineRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        paddingVertical: 8,
        borderBottomWidth: 1,
        borderBottomColor: '#f0dfe8',
    },
    detailLineInfo: {
        flex: 1,
        marginRight: 8,
    },
    detailLineText: {
        fontSize: 11,
        fontWeight: '600',
        color: '#222',
    },
    detailLineMeta: {
        marginTop: 0,
        fontSize: 9,
        color: '#777',
    },
    detailLineCost: {
        width: 72,
        textAlign: 'right',
        fontSize: 10,
        fontWeight: '700',
    },
    detailTotalRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingTop: 0,
        marginTop: 0,
    },
    detailTotalLabel: {
        fontSize: 13,
        fontWeight: '700',
    },
    detailTotalValue: {
        fontSize: 13,
        fontWeight: '700',
    },
    detailMetricRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        paddingTop: 8,
    },
    detailFooterPanel: {
        borderTopWidth: 1,
        borderTopColor: '#ead4e0',
        paddingTop: 4,
    },
    saleEditorLabel: {
        fontSize: 12,
        fontWeight: '800',
        color: '#7a5e6e',
        marginBottom: 6,
    },
    saleEditorRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 8,
        marginBottom: 8,
    },
    saleInputWrapper: {
        flex: 1,
        minHeight: 40,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#f0c9dc',
        backgroundColor: '#fff8fb',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 10,
    },
    saleCurrencyPrefix: {
        fontSize: 14,
        fontWeight: '700',
        color: '#8f5d76',
        marginRight: 4,
    },
    saleAmountInput: {
        flex: 1,
        fontSize: 14,
        fontWeight: '700',
        color: '#222',
        paddingVertical: 8,
    },
    saleSaveButton: {
        minHeight: 40,
        paddingHorizontal: 14,
        borderRadius: 12,
        backgroundColor: '#e91e63',
        alignItems: 'center',
        justifyContent: 'center',
    },
    saleSaveButtonDisabled: {
        opacity: 0.7,
    },
    saleSaveButtonText: {
        fontSize: 12,
        fontWeight: '800',
        color: '#fff',
    },
    detailMetricLabel: {
        fontSize: 12,
        fontWeight: '700',
        color: '#666',
    },
    detailMetricValue: {
        fontSize: 12,
        fontWeight: '700',
        color: '#333',
    },
    detailProfitValue: {
        color: '#2b8a5b',
    },
    detailLossValue: {
        color: '#c0392b',
    },
    detailHintText: {
        marginTop: 8,
        color: '#777',
        fontSize: 12,
        textAlign: 'center',
    },
});
