import { StyleSheet } from 'react-native';

export const ingredientsStyles = StyleSheet.create({
    container: {
        flex: 1,
        padding: 16,
        backgroundColor: '#faf5ff',
    },
    title: {
        fontSize: 26,
        fontWeight: '800',
        marginBottom: 16,
        color: '#1a1a1a',
    },
    form: {
        marginBottom: 18,
        gap: 10,
        backgroundColor: '#fff',
        padding: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#f0d7eb',
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowOffset: { width: 0, height: 2 },
        shadowRadius: 6,
        elevation: 2,
    },
    input: {
        borderWidth: 1,
        borderColor: '#e0c4d9',
        borderRadius: 8,
        paddingHorizontal: 10,
        paddingVertical: 10,
        backgroundColor: '#fff',
        fontSize: 14,
    },
    sectionTitle: {
        fontSize: 18,
        fontWeight: '700',
        marginBottom: 10,
        color: '#333',
    },
    itemRow: {
        paddingVertical: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#f0e0f0',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        gap: 10,
    },
    itemName: {
        fontSize: 16,
        fontWeight: '600',
    },
    itemSubtitle: {
        color: '#777',
    },
    emptyText: {
        color: '#777',
        marginTop: 8,
    },
    submitButton: {
        minHeight: 50,
        borderRadius: 12,
        backgroundColor: '#e91e63',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        gap: 8,
        shadowColor: '#e91e63',
        shadowOpacity: 0.18,
        shadowOffset: { width: 0, height: 6 },
        shadowRadius: 10,
        elevation: 3,
    },
    submitButtonEditing: {
        backgroundColor: '#d81b60',
    },
    submitButtonText: {
        color: '#fff',
        fontSize: 15,
        fontWeight: '700',
    },
    deleteButton: {
        width: 36,
        height: 36,
        borderRadius: 10,
        backgroundColor: '#ef5350',
        alignItems: 'center',
        justifyContent: 'center',
    },
});
